In [1]:
import numpy as np

## Array Creation:
o Create a 1-dimensional array of integers from 1 to 10. <br>
o Create a 2-dimensional array with random float values of shape (3, 4).<br>
o Create a 3-dimensional array of zeros with shape (2, 3, 4).<br>

In [29]:
array1 = np.arange(1,11)
array2 =np.random.randn(3,4)
array3 = np.zeros((2,3,4))

## 2. Array Operations:
o Given two 1-dimensional arrays, perform element-wise addition,
subtraction, multiplication, and division. <br>
o Calculate the mean, median, and standard deviation of a given 1-
dimensional array.<br>
o Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).<br>

In [17]:
arr1= np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(array1)
array1 = arr1+arr2
print(array1)
array1 = arr1-arr2
print(array1)
array1 = arr1*arr2
print(array1)
array1 = arr1/arr2
print(array1)


[-5.11111111 -4.66666667 -4.22222222 -3.77777778 -3.33333333 -2.88888889
 -2.44444444 -2.         -1.55555556 -1.11111111]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [19]:
array1 = np.arange(0,12)
print(array1)
mean1= array1.mean()
print(mean1)
median1= np.percentile(array1,50)
print(median1)
sd1 = array1.std()
print(sd1)
arr1 = array1.reshape(3,4)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5.5
5.5
3.452052529534663
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 3. Array Indexing and Slicing:
o Extract the first row and last column of a 2-dimensional array. <br>
o Reverse the order of elements in a 1-dimensional array.<br>
o Select elements from a 2-dimensional array that satisfy a specific<br>
condition (e.g., values greater than a certain threshold).<br>

In [43]:
print(array2[0,:])
print(array2[:,-1])
print(array1[-1::-1])
print(array2[array2>=1])

[-0.01311161 -0.34760898  0.39569907 -0.29947888]
[-0.29947888  1.08902849  0.27298027]
[10  9  8  7  6  5  4  3  2  1]
[1.56811433 1.08902849 1.22626396]


## 4. Array Broadcasting:
o Add a scalar value to each element of a 2-dimensional array.<br>
o Multiply a 1-dimensional array with a 2-dimensional array, leveraging<br>
NumPy's broadcasting rules.<br>

In [50]:
print(array2+2)
onedArr = np.arange(1,6)
print(onedArr)
twodArr = np.arange(0,10).reshape(2,5)
print(twodArr)
print(twodArr*onedArr)

[[1.98688839 1.65239102 2.39569907 1.70052112]
 [3.56811433 2.86787832 1.5867293  3.08902849]
 [2.33577505 3.22626396 2.05614411 2.27298027]]
[1 2 3 4 5]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  2  6 12 20]
 [ 5 12 21 32 45]]


## 5. Linear Algebra:
o Calculate the dot product of two 1-dimensional arrays.<br>
o Compute the matrix multiplication of two 2-dimensional arrays.<br>
o Find the inverse and determinant of a square matrix.<br>

In [ ]:
arr1 = np.array([1,2,3.])
arr2 = np.array([4,5,6.])
print(np.dot(arr1,arr2))

mat1 = np.matrix([[1,2,3],[4,5,6],[7,8,10.]])
mat2 = mat1+1
print(np.matmul(mat1,mat2))

print(np.linalg.det(mat1))
invmat1=np.linalg.inv(mat1)
print(mat1@invmat1)
# close to one


# but if I
mat1 = np.matrix([[1,2,3],[4,5,6],[7,8,9.]])
print(np.linalg.det(mat1)) # near to zero
invmat1=np.linalg.inv(mat1)
print(mat1@invmat1) # Weried result cause of near zero determinant and floating point magic


32.0
[[ 36.  42.  51.]
 [ 81.  96. 117.]
 [134. 159. 194.]]
-3.000000000000001
[[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 4.44089210e-16  8.88178420e-16  1.00000000e+00]]
-9.51619735392994e-16
[[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]
